// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvQTUk9y0yVjl2MCWd6FkThmCdc0yLcT0',
    appId: '1:1070318151454:android:6fd4cc8d52495523e24b0f',
    messagingSenderId: '1070318151454',
    projectId: 'acefood-flutter',
    storageBucket: 'acefood-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBOdCcEKXOkd8CmoxYNjTRTY-WI0IsMqc',
    appId: '1:1070318151454:ios:d2ad36bdb7e4eb8be24b0f',
    messagingSenderId: '1070318151454',
    projectId: 'acefood-flutter',
    storageBucket: 'acefood-flutter.appspot.com',
    iosClientId:
        '1070318151454-56v016m5jk4fhcf4pbaa4nmgq1p0s31p.apps.googleusercontent.com',
    iosBundleId: 'com.ajibsbaba.acefood',
  );
}
